name: 独立部署到 Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出您的独立仓库
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          # 明确指定您的仓库（非上游）
          repository: ${{ github.repository }} 
          ref: main

      # 2. 直接部署到Cloudflare（无同步步骤）
      - name: 部署到 Cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "libretvgb"  # 您自己的Cloudflare项目
          directory: '.'            # 部署整个仓库
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
