name: 部署到Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: 部署
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # 添加 Node.js 设置步骤（即使不需要构建）
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 部署到 Cloudflare
      - name: 部署到 Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          # 关键修复：直接从 secrets 获取凭证
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "LibreTV"  # 替换为实际名称
          directory: '.'  # 部署整个仓库
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
