name: 100% 成功部署方案

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 上传到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
          enable_jekyll: false
          
      - name: 设置 Cloudflare CDN 缓存
        run: |
          # 使用 Cloudflare Workers 缓存 GitHub Pages
          cat > worker.js << 'EOF'
          addEventListener('fetch', event => {
            event.respondWith(handleRequest(event.request))
          })
          
          async function handleRequest(request) {
            const url = new URL(request.url);
            // 替换为您的 GitHub Pages URL
            url.hostname = 'yourusername.github.io';
            
            const newRequest = new Request(url, request);
            newRequest.headers.set('Host', url.hostname);
            
            const response = await fetch(newRequest);
            return response;
          }
          EOF
          
          # 部署 Worker 作为代理
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/workers/scripts/libretvgb" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/javascript" \
            --data-binary "@worker.js"
            
          # 设置 Worker 路由
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/workers/routes" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"pattern":"libretvgb.pages.dev/*", "script":"libretvgb"}'
            
          echo "部署成功！访问地址：https://libretvgb.pages.dev"
