name: Cloudflare 完美部署

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: 检出仓库
        uses: actions/checkout@v4
        
      # 2. 安装 Cloudflare CLI
      - name: 安装 Wrangler
        run: npm install -g wrangler@3.22.0
        
      # 3. 验证项目状态
      - name: 验证项目存在
        run: |
          # 列出所有 Pages 项目
          wrangler pages project list
          
          # 检查目标项目是否存在
          if ! wrangler pages project list | grep -q libretvgb; then
            echo "::error::项目 'libretvgb' 不存在，正在创建..."
            wrangler pages project create libretvgb --production-branch=main
          else
            echo "项目 'libretvgb' 已存在"
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      # 4. 强制部署
      - name: 强制部署
        run: |
          # 强制部署（忽略所有警告）
          wrangler pages deploy . \
            --project-name=libretvgb \
            --branch=main \
            --commit-dirty=true \
            --skip-caching \
            --no-verify
            
          echo "::notice::部署成功！访问地址：https://libretvgb.pages.dev"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
