name: 自动同步到 Cloudflare

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出最新代码
      - name: 检出仓库
        uses: actions/checkout@v4
        
      # 步骤2：安装 Cloudflare CLI（绕过 API 问题）
      - name: 安装 Wrangler
        run: npm install -g wrangler@3.22.0
        
      # 步骤3：验证账户
      - name: 验证 Cloudflare 凭证
        run: |
          # 验证账户ID格式
          if [[ ! "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" =~ ^[a-f0-9]{32}$ ]]; then
            echo "::error::账户ID格式错误！必须是32位十六进制字符"
            echo "正确示例：e111f222g333h444i555j666k777l888"
            exit 1
          fi
          
          # 验证API令牌
          wrangler whoami
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      # 步骤4：强制同步部署
      - name: 强制同步到 Cloudflare
        run: |
          # 创建或更新项目
          wrangler pages project create libretvgb --production-branch=main || true
          
          # 强制部署最新代码
          wrangler pages deploy . \
            --project-name=libretvgb \
            --branch=main \
            --commit-dirty=true \
            --skip-caching
          
          # 清除 Cloudflare 缓存
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
            
          echo "::notice::同步成功！访问地址：https://libretvgb.pages.dev"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
