name: 直接部署到Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  PROJECT_NAME: "LibreTV"

jobs:
  deploy:
    name: 直接部署
    runs-on: ubuntu-latest

    steps:
      # 步骤1: 检出代码
      - name: 检出仓库
        uses: actions/checkout@v4

      # 步骤2: 直接部署整个仓库
      - name: 部署到Cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PROJECT_NAME }}
          directory: '.'  # 部署整个仓库
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
